#!/usr/bin/env python3
from socket import *
import sys 
def toSock(argm):
    ## Set the socket parameters
    host = '127.0.0.1' # Update it to your IP.
    port = 5500
    #If conn.recv() returns an empty bytes object, b'', then the client closed the connection and the loop is terminated. The with statement is used with conn to automatically close the socket at the end of the block.
    with socket(AF_INET, SOCK_STREAM) as tcpsoc:
        tcpsoc.connect((host, port)) #if connection is not ready then it will not connect
        tcpsoc.send(str.encode(argm)) #we receiv it as string hence need to convert it into bytes
        #can use to check if the data received at the receivers end
        #data = tcpsoc.recv(1024)  

if __name__ == "__main__":
    hexdata = sys.argv[1] # when you run the script pass it as argument
    toSock(hexdata)
